name: Build

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  TAG_NAME: latest

jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:sid
    strategy:
      fail-fast: false
      matrix:
        u-boot-version:
          - t10n
          - t10l
          - t10n_msc0
          - t20n
          - t20l
          - t20x
          - t20n_msc0
          - t21n
          - t21n_msc0
          - t23n
          - t23n_msc0
          - t30n
          - t30l
          - t30x
          - t30a
          - t30a1
          - t30n_msc0
          - t31n
          - t31l
          - t31lc
          - t31x
          - t31a
          - t31al
          - t31n_msc0
          - t31a_msc0
          - t31al_msc0
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y --no-install-recommends --no-install-suggests build-essential gcc-13 gcc-13-mipsel-linux-gnu lzop u-boot-tools git make ca-certificates
          CROSS_COMPILE=mipsel-linux-gnu-; VER=${1:-13}; for app in cpp gcc gcc-ar gcc-nm gcc-ranlib gcov gcov-dump gcov-tool lto-dump; do if update-alternatives --query ${CROSS_COMPILE}${app} >/dev/null; then update-alternatives --set ${CROSS_COMPILE}${app} /usr/bin/${CROSS_COMPILE}${app}-${VER}; else update-alternatives --install /usr/bin/${CROSS_COMPILE}${app} ${CROSS_COMPILE}${app} /usr/bin/${CROSS_COMPILE}${app}-${VER} 1; fi; done; echo "Done"

      - name: u-boot-ingenic Build
        run: |
          git clone https://github.com/gtxaspec/u-boot-ingenic.git --depth 1
          cd u-boot-ingenic
          cp -f .github/scripts/u-boot-ingenic.sh u-boot-ingenic.sh
          VERSION=${{ matrix.u-boot-version }}
          bash u-boot-ingenic.sh $VERSION

      - name: Check if file exists
        id: check-file
        run: |
          FILE=$(find . -type f -name "u-boot-${{ matrix.u-boot-version }}-universal.bin")
          if [ -z "$FILE" ]; then
            echo "::error::File u-boot-${{ matrix.u-boot-version }}-universal.bin does not exist."
            echo "FILE_FOUND=false" >> $GITHUB_ENV
            exit 1
          else
            echo "Found file: $FILE"
            echo "FILE_FOUND=true" >> $GITHUB_ENV
          fi
        shell: bash --noprofile --norc -e -o pipefail {0}
        env:
          TAG_NAME: ${{ env.TAG_NAME }}

      - name: Upload ${{ matrix.u-boot-version }}
        if: env.FILE_FOUND == 'true'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          files: |
            u-boot-ingenic/output/u-boot-${{ matrix.u-boot-version }}-universal.bin
